city_key: 'example'
sys_access_user: 'rikki'
sys_access_user_key_file: '~/.ssh/id_rsa.pub'
mysql_root_user: 'root'
mysql_root_password: 'SECRET'
mysql_app_user: application
mysql_app_password: SECRET
mysql_app_db_name: application
app_user: admin
app_hostname: https://subdomain.hostname.com
app_password: SECRET
app_email_from_address: admin@freecle.org
app_calendar_embed_url:
app_email_smtp_host: host@host.com
app_email_smtp_user: user
app_email_smtp_password: SECRET
ansible_hostname: localhost
apache_vhosts:
  - {
    servername: "subdomain.hostname.com",
    documentroot: "/var/www/html"
  }
apache_vhosts_ssl:
  - {
    servername: "subdomain.hostname.com",
    documentroot: "/var/www/html",
    certificate_file: "/root/memoryhole.crt",
    certificate_key_file: "/root/memoryhole.key"
  }
apache_mods_enabled:
  - rewrite.load
  - ssl.load
