- name: restart mysql-server
  service: name=mysql state=restarted
  become: yes
  become_method: sudo

- name: restart apache
  service: name=apache2 state=restarted
  become: yes
  become_method: sudo
