# This script provisions the server, thus we tell ansible to use root
# When using the CIS ansible roles, root ssh login is disbled, thus why init creates
# a new sudo user
- hosts: memoryhole
  remote_user: root
  become: yes

  vars_files:
    - "../cities/{{ city_key }}/config.yml"

  pre_tasks:
    - include: tasks/init.yml

  handlers:
    - include: handlers/main.yml
