- name: Copy memoryhole from app/ to the webroot
  synchronize: src=../app/ dest=/var/www/html delete=yes rsync_opts=--recursive,--force
  become: yes
  become_user: root
  no_log: True # no_log suppresses the output
  tags:
    - application
    - always

- name: Copy over config.php file w/ mysql creds
  template: src=templates/config.php.j2 dest=/var/www/html/config.php
  become: yes
  become_user: root
  tags:
    - application

- name: create mysql app user
  mysql_user:
    name: "{{ mysql_app_user }}"
    password: "{{ mysql_app_password }}"
    login_user: "{{ mysql_root_user }}"
    login_password: "{{ mysql_root_password }}"
    host: "localhost"
    priv: "{{ mysql_app_db_name }}.*:ALL"
    state: present
    login_host: localhost
  tags:
    - application

- name: create mysql app db
  become: yes
  become_user: root
  mysql_db:
    name: "{{ mysql_app_db_name }}"
    state: present
    login_user: "{{ mysql_root_user }}"
    login_password: "{{ mysql_root_password }}"
  register: dbcreated
  tags:
    - application

- name: Copy over db.sql file w/ config creds
  template: src=templates/db.sql.j2 dest=/root/db.sql
  become: yes
  tags:
    - application
    - schema

- name: create schema
  mysql_db:
    name: "{{ mysql_app_db_name }}"
    target: /root/db.sql
    state: import
    login_user: "{{ mysql_root_user }}"
    login_password: "{{ mysql_root_password }}"
  tags:
    - application
    - schema

- name: delete import
  file:
    path: /root/db.sql
    state: absent

- name: set application-wide folder ownership
  file: path=/var/www/html group=www-data owner=www-data state=directory recurse=yes

- name: set special folder ownership and permissions
  file: 'path=/var/www/html/{{ item }} mode=0755 recurse=yes state=directory group=www-data owner=www-data'
  become: yes
  with_items:
    - cache
    - custom
    - data
    - modules
  tags:
    - application

- name: ok and config_override.php can be writeable (for UI-driven config changes) but NOT config.php with db credentials nope sorry
  file: path=/var/www/html/config_override.php mode=664
  tags:
    - application
  notify: restart apache

- name: Add php.ini configs - Memory Limit
  lineinfile: dest=/etc/php5/apache2/php.ini regexp="^upload_max" line="upload_max = 10M"
  tags:
    - application

- name: Add php.ini configs - Timezone
  lineinfile: dest=/etc/php5/apache2/php.ini regexp="^;date.timezone" line="date.timezone = America/New_York"
  become: yes
  tags:
    - application
