- name: Copy certificate Key
  copy: 'src=../../cities/{{ city_key }}/certificates/memoryhole.key dest=/root/memoryhole.key owner=root group=root'
  tags:
  - application

- name: Copy certificate
  copy: 'src=../../cities/{{ city_key }}/certificates/memoryhole.crt dest=/root/memoryhole.crt owner=root group=root'
  notify: reload apache
  tags:
  - application
