---

- name: Install system packages
  apt: pkg={{item}} state=latest
  with_items:
  - apache2
  - apache2-utils
  - php5-mysql
  - php5
  - php5-gd
  - curl
  - wget
  - gzip
  - rsync
  - openssl
  - vim
  - php-pear
  - gcc
  - make
  - libapache2-mod-php5
  - ansible
  - mysql-server
  - python-mysqldb
  tags: yum

- name: Enable wheel for CentOS
  lineinfile: 'dest=/etc/sudoers state=present regexp="^%wheel" line="%wheel ALL=(ALL) NOPASSWD: ALL"'

- name: Instantiate non-root access user
  user: name={{ sys_access_user }} group=sudo generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa

- name: Provision authorized key
  authorized_key: user={{ sys_access_user }} key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

- name: Disable TTY for non-root access user
  lineinfile: 'line="Defaults:{{ sys_access_user }} !requiretty" dest="/etc/sudoers"'
